//! The answer list, and the only thing in this module that is not logic.
//!
//! Common five-letter words, deliberately short. A module's whole wasm is
//! downloaded and hashed at install, so a dictionary of tens of thousands
//! would dwarf the code that uses it for no gain: a guessing game needs
//! answers somebody has a chance of knowing, not every word that exists.
//!
//! Any five-letter guess is accepted, though. Rejecting a real word missing
//! from a short list is the most annoying thing a game like this can do.

pub const WORDS: [&str; 570] = [
    "about", "above", "actor", "acute", "admit", "adopt", "adult", "after",
    "again", "agent", "agree", "ahead", "alarm", "album", "alert", "alike",
    "alive", "allow", "alone", "along", "alter", "among", "anger", "angle",
    "angry", "apart", "apple", "apply", "arena", "argue", "arise", "armed",
    "arrow", "aside", "asset", "avoid", "awake", "award", "aware", "badly",
    "baker", "bases", "basic", "basis", "beach", "began", "begin", "begun",
    "being", "below", "bench", "birth", "black", "blame", "blank", "blast",
    "blind", "block", "blood", "board", "boost", "booth", "bound", "brain",
    "brand", "brass", "brave", "bread", "break", "breed", "brief", "bring",
    "broad", "broke", "brown", "brush", "build", "built", "buyer", "cable",
    "cache", "cargo", "carry", "catch", "cause", "chain", "chair", "chalk",
    "charm", "chart", "chase", "cheap", "check", "chess", "chest", "chief",
    "child", "china", "chose", "civil", "claim", "class", "clean", "clear",
    "clerk", "click", "cliff", "climb", "clock", "close", "cloth", "cloud",
    "coach", "coast", "could", "count", "court", "cover", "crack", "craft",
    "crash", "cream", "crime", "cross", "crowd", "crown", "curve", "cycle",
    "daily", "dance", "dated", "dealt", "death", "debut", "delay", "depth",
    "doing", "doubt", "dozen", "draft", "drama", "drank", "drawn", "dream",
    "dress", "drill", "drink", "drive", "drove", "dying", "eager", "early",
    "earth", "eight", "elect", "elite", "empty", "enemy", "enjoy", "enter",
    "entry", "equal", "error", "event", "every", "exact", "exist", "extra",
    "faith", "false", "fault", "fiber", "field", "fifth", "fifty", "fight",
    "final", "first", "fixed", "flame", "flash", "fleet", "floor", "focus",
    "force", "forge", "forth", "forty", "forum", "found", "frame", "fraud",
    "fresh", "front", "fruit", "fully", "funny", "giant", "given", "glass",
    "globe", "glory", "grace", "grade", "grain", "grand", "grant", "grass",
    "grave", "great", "green", "gross", "group", "grown", "guard", "guess",
    "guest", "guide", "happy", "harsh", "heart", "heavy", "hedge", "hence",
    "hobby", "honey", "honor", "horse", "hotel", "house", "human", "humor",
    "hurry", "ideal", "image", "imply", "index", "inner", "input", "issue",
    "joint", "judge", "known", "label", "labor", "large", "laser", "later",
    "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon",
    "level", "light", "limit", "linen", "liver", "local", "logic", "loose",
    "lower", "lucky", "lunch", "lying", "magic", "major", "maker", "maple",
    "march", "match", "maybe", "mayor", "meant", "medal", "media", "metal",
    "meter", "might", "minor", "minus", "mixed", "model", "money", "month",
    "moral", "motor", "mount", "mouse", "mouth", "movie", "music", "naked",
    "nerve", "never", "newly", "night", "noble", "noise", "north", "noted",
    "novel", "nurse", "ocean", "offer", "often", "onion", "order", "other",
    "ought", "outer", "owner", "paint", "panel", "paper", "party", "peace",
    "phase", "phone", "photo", "piano", "piece", "pilot", "pitch", "place",
    "plain", "plane", "plant", "plate", "point", "pound", "power", "press",
    "price", "pride", "prime", "print", "prize", "proof", "proud", "prove",
    "pulse", "punch", "pupil", "quart", "queen", "query", "quick", "quiet",
    "quite", "quote", "radio", "raise", "range", "rapid", "ratio", "reach",
    "ready", "realm", "rebel", "refer", "relax", "reply", "rider", "ridge",
    "rifle", "right", "rigid", "rival", "river", "robot", "rocky", "roman",
    "rough", "round", "route", "royal", "rural", "sadly", "salad", "sales",
    "salon", "sauce", "scale", "scene", "scope", "score", "sense", "serve",
    "seven", "shade", "shake", "shall", "shape", "share", "sharp", "sheep",
    "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shoot",
    "shore", "short", "shown", "sight", "silly", "since", "sixth", "sixty",
    "skill", "sleep", "slide", "slope", "small", "smart", "smile", "smoke",
    "snake", "solar", "solid", "solve", "sorry", "sound", "south", "space",
    "spare", "speak", "speed", "spend", "spent", "spice", "spine", "spite",
    "split", "spoke", "sport", "squad", "staff", "stage", "stake", "stand",
    "stare", "start", "state", "steam", "steel", "steep", "steer", "stick",
    "still", "stock", "stone", "stood", "store", "storm", "story", "strip",
    "stuck", "study", "stuff", "style", "sugar", "suite", "super", "sweet",
    "table", "taken", "taste", "taxes", "teach", "teeth", "thank", "theft",
    "their", "theme", "there", "these", "thick", "thing", "think", "third",
    "those", "three", "threw", "throw", "tiger", "tight", "timer", "tired",
    "title", "today", "token", "tooth", "topic", "total", "touch", "tough",
    "tower", "trace", "track", "trade", "trail", "train", "trait", "treat",
    "trend", "trial", "tribe", "trick", "tried", "tries", "truck", "truly",
    "trust", "truth", "twice", "twist", "ultra", "uncle", "under", "union",
    "unity", "until", "upper", "upset", "urban", "usage", "usual", "valid",
    "value", "video", "villa", "virus", "visit", "vital", "vivid", "vocal",
    "voice", "waste", "watch", "water", "wheat", "wheel", "where", "which",
    "while", "white", "whole", "whose", "woman", "world", "worry", "worse",
    "worst", "worth", "would", "wound", "write", "wrong", "wrote", "yield",
    "young", "youth",
];
